version: "3.3"
networks:
  techmaster-jitsi:
    external: true

services:
  game:
    image: registry.techmaster.vn/techmaster-game:latest
    networks:
      - techmaster-jitsi
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname == ubuntu
      labels:
        - traefik.port=8382
        - "traefik.enable=true"
        - "traefik.backend=game"
        - "traefik.frontend.rule=Host:codegame.techmaster.vn"
        - "traefik.docker.network=techmaster-jitsi"